# Generated by Django 4.0.10 on 2026-09-19 15:34

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_name", models.CharField(blank=True, max_length=200, null=True)),
                ("venue_image", models.ImageField(blank=True, upload_to="venues/")),
                ("address1", models.CharField(blank=True, max_length=100, null=True)),
                ("address2", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, default="U.S.A.", max_length=100, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("ltlng", models.CharField(blank=True, max_length=100, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["venue_name"],
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("date", models.DateTimeField()),
                ("doors_time", models.TimeField(blank=True, null=True)),
                (
                    "ticket_price",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ticket_url", models.URLField(blank=True, null=True)),
                ("ages", models.CharField(blank=True, max_length=100, null=True)),
                ("opener", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "poster",
                    models.FileField(blank=True, null=True, upload_to="posters/"),
                ),
                ("fb_event", models.CharField(blank=True, max_length=200, null=True)),
                ("attendance", models.IntegerField(blank=True, null=True)),
                (
                    "gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("gross_itemized", models.BooleanField(default=False)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "food_buyout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "travel_buyout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lodging_buyout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "other_buyout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gross_method",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("check", "Check")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        blank=True,
                        choices=[("client", "Client"), ("agent", "Agent")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("payee_check_no", models.IntegerField(blank=True, null=True)),
                (
                    "commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("commission_withheld", models.BooleanField(default=False)),
                (
                    "commission_percentage",
                    models.IntegerField(blank=True, default=10, null=True),
                ),
                ("commission_check_no", models.IntegerField(blank=True, null=True)),
                ("commission_paid", models.BooleanField(default=False)),
                (
                    "sound_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sound_check_no", models.IntegerField(blank=True, null=True)),
                (
                    "in_ears_cost",
                    models.IntegerField(
                        blank=True,
                        choices=[(80, "$80"), (130, "$130")],
                        default=130,
                        null=True,
                    ),
                ),
                ("in_ears_check_no", models.IntegerField(blank=True, null=True)),
                ("costs_itemized", models.BooleanField(default=False)),
                (
                    "print_ship_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ads_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "to_account",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("subs", models.BooleanField(default=False)),
                (
                    "settlement_sheet",
                    sorl.thumbnail.fields.ImageField(
                        blank=True, null=True, upload_to="receipts/"
                    ),
                ),
                ("payout_notes", models.TextField(blank=True, null=True)),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="show_in_tour",
                        to="shows.tour",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="shows.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
