version: "3.7"

volumes:
  static_volume:
  media_volume:

services:
  web:
    container_name: foreverland
    restart: always
    build: ./web
    expose:
      - 8000
    env_file:
      - .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=foreverland.settings.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/ubuntu/app/staticfiles
      - media_volume:/home/ubuntu/app/mediafiles
    command: bash -c "python3 manage.py collectstatic --noinput && python3 manage.py compress && python3 manage.py migrate && gunicorn foreverland.wsgi:application --bind 0.0.0.0:8000"
  db:
    container_name: foreverland_db
    image: mysql:5.7
    restart: always
    env_file:
      - .env.prod
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - static_volume:/home/ubuntu/app/staticfiles
      - media_volume:/home/ubuntu/app/mediafiles
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
