version: "3.7"

volumes:
  db_data:
  static_volume:
  media_volume:

services:
  web:
    container_name: foreverland
    restart: always
    build: ./web
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    command: gunicorn foreverland.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE='foreverland.settings.prod'
    environment:
      - ENV=prod
  db:
    container_name: foreverland_db
    image: mysql:5.7
    restart: always
    env_file:
      - .env.prod
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web