# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-10-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fidouche', '0002_fiduciary_fiduciarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='ssn',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='SSN/EIN'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='check_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Check #'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='fidouche.ExpenseCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_img',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='ssn',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='SSN/EIN'),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='income',
            name='check_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Check #'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='ssn',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='SSN#'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='ssn',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='SSN/EIN'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='tourexpense',
            name='check_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Check #'),
        ),
        migrations.AlterField(
            model_name='tourexpense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='tourexpense',
            name='receipt_img',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
