# Generated by Django 4.0.10 on 2026-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_first', models.CharField(blank=True, max_length=50, null=True)),
                ('display_last', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, choices=[('v', 'Vocal'), ('h', 'Horn'), ('r', 'Rhythm')], max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('bio', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, max_length=16, null=True, verbose_name='SSN#')),
                ('partner', models.BooleanField(default=False)),
                ('date_partner_joined', models.DateField(blank=True, null=True, verbose_name='Became a Partner')),
                ('date_partner_left', models.DateField(blank=True, null=True, verbose_name='Left Partnership')),
            ],
            options={
                'ordering': ['-active', '-section', 'display_first'],
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, max_length=16, null=True, verbose_name='SSN#')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
