from django.urls import path
from fidouche.views import (
    financial_dashboard,
    gigs_by_year,
    gigs_year_over_year,
    gig_finances,
    gig_finances_view,
    tour_list,
    tour_detail,
    expenses_list,
    all_expenses_list,
    expense_details,
    expense_create,
    expense_delete,
    income_list,
    all_income_list,
    income_details,
    income_create,
    income_delete,
    finance_reports,
    tax_reports,
    member_payments,
    sub_payments,
    vendor_payments,
    production_payments,
    venue_map,
    venue_map_data,
)

urlpatterns = [
    path("$", financial_dashboard, {}, name="financial_dashboard"),
    path("(?P<year>\d{4})/", gigs_by_year, {}, name="gigs_by_year"),
    path("gigs/year-over-year", gigs_year_over_year, {}, name="gigs_year_over_year"),
    path("gigs/(?P<gig_id>\d+)/$", gig_finances, {}, name="gig_finances"),
    path("gigs/view/(?P<gig_id>\d+)/$", gig_finances_view, {}, name="gig_finances_view"),
    path("tours/$", tour_list, {}, name="tour_list"),
    path("tours/(?P<tour_id>\d+)/$", tour_detail, {}, name="tour_detail"),
    path("expenses/year/(?P<year>\d{4})/", expenses_list, {}, name="expenses_list"),
    path("expenses/$", all_expenses_list, {}, name="all_expenses_list"),
    path("expenses/(?P<expense_id>\d+)/$", expense_details, {}, name="expense_details"),
    path("expenses/create/$", expense_create, {}, name="expense_create"),
    path(
        "expenses/delete/(?P<expense_id>\d+)/$",
        expense_delete,
        {},
        name="expense_delete",
    ),
    path("income/year/(?P<year>\d{4})/", income_list, {}, name="income_list"),
    path("income/$", all_income_list, {}, name="all_income_list"),
    path("income/(?P<income_id>\d+)/$", income_details, {}, name="income_details"),
    path("income/create/$", income_create, {}, name="income_create"),
    path(
        "income/delete/(?P<income_id>\d+)/$", income_delete, {}, name="income_delete"
    ),
    path("reports/$", finance_reports, {}, name="finance_reports"),
    path("tax-reports/$", tax_reports, {}, name="tax_reports"),
    path(
        "member-payments/(?P<member_id>\d+)$",
        member_payments,
        {},
        name="member_payments",
    ),
    path("sub-payments/(?P<sub_id>\d+)$", sub_payments, {}, name="sub_payments"),
    path(
        "vendor-payments/(?P<vendor_id>\d+)$",
        vendor_payments,
        {},
        name="vendor_payments",
    ),
    path(
        "production-payments/(?P<company_id>\d+)$",
        production_payments,
        {},
        name="production_payments",
    ),
    path("map/$", venue_map, {}, name="venue_map"),
    path("map-data/$", venue_map_data, {}, name="venue_map_data"),
]
