# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='shows.Show')),
            ],
        ),
        migrations.CreateModel(
            name='SetlistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Setlist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('original_artist', models.CharField(blank=True, max_length=200, null=True)),
                ('original_album', models.CharField(blank=True, max_length=200, null=True)),
                ('release_year', models.CharField(blank=True, max_length=200, null=True)),
                ('display', models.BooleanField(default=True)),
                ('foh_notes', models.TextField(blank=True, null=True, verbose_name=b'Notes for FOH')),
                ('singer', models.ManyToManyField(blank=True, null=True, related_name='singer', to='members.Member')),
            ],
        ),
        migrations.AddField(
            model_name='setlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(through='songs.SetlistSong', to='songs.Song'),
        ),
    ]
