# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20170526_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
