# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_set_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='setsong',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-display', 'name']},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singers',
        ),
        migrations.AlterField(
            model_name='set',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setsong',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
