# Generated by Django 4.0.10 on 2026-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show',
            field=models.ManyToManyField(blank=True, to='shows.show'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='albums',
            field=models.ManyToManyField(blank=True, to='media.album'),
        ),
        migrations.AddField(
            model_name='image',
            name='show',
            field=models.ManyToManyField(blank=True, to='shows.show'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.tag'),
        ),
        migrations.AddField(
            model_name='download',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.tag'),
        ),
        migrations.AddField(
            model_name='album',
            name='show',
            field=models.ManyToManyField(blank=True, to='shows.show'),
        ),
    ]
