# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('shows', '0001_initial'),
        ('fidouche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourexpense',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Tour'),
        ),
        migrations.AddField(
            model_name='subpayment',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpayment', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='subpayment',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='members.Sub'),
        ),
        migrations.AddField(
            model_name='productionpayment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidouche.ProductionCategory'),
        ),
        migrations.AddField(
            model_name='productionpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_payment', to='fidouche.ProductionCompany'),
        ),
        migrations.AddField(
            model_name='productionpayment',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_payment', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='productioncategory',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_category', to='fidouche.TaxExpenseCategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='members.Member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='fidouche.TaxExpenseCategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='fidouche.ExpenseCategory', verbose_name=b'Category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='fidouche.Payee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment', to='fidouche.Agent'),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment', to='shows.Show'),
        ),
        migrations.AlterUniqueTogether(
            name='subpayment',
            unique_together=set([('show', 'sub')]),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set([('show', 'member')]),
        ),
        migrations.AlterUniqueTogether(
            name='commissionpayment',
            unique_together=set([('show', 'agent')]),
        ),
    ]
