# Generated by Django 4.0.10 on 2026-09-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('original_artist', models.CharField(blank=True, max_length=200, null=True)),
                ('original_album', models.CharField(blank=True, max_length=200, null=True)),
                ('release_year', models.CharField(blank=True, max_length=200, null=True)),
                ('display', models.BooleanField(default=True)),
                ('foh_notes', models.TextField(blank=True, null=True, verbose_name='Notes for FOH')),
                ('singer', models.ManyToManyField(blank=True, related_name='singer', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SetlistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.setlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
        migrations.AddField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(through='songs.SetlistSong', to='songs.song'),
        ),
    ]
