# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fidouche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('doors_time', models.TimeField(blank=True, null=True)),
                ('ticket_price', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_url', models.URLField(blank=True, null=True)),
                ('ages', models.CharField(blank=True, max_length=100, null=True)),
                ('opener', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('poster', models.FileField(blank=True, null=True, upload_to=b'posters/')),
                ('fb_event', models.CharField(blank=True, max_length=200, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_itemized', models.BooleanField(default=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lodging_buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_method', models.CharField(blank=True, choices=[(b'cash', b'Cash'), (b'check', b'Check')], default=b'cash', max_length=100, null=True)),
                ('payer', models.CharField(blank=True, choices=[(b'client', b'Client'), (b'agent', b'Agent')], default=b'client', max_length=100, null=True)),
                ('payee_check_no', models.IntegerField(blank=True, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_withheld', models.BooleanField(default=True)),
                ('commission_percentage', models.IntegerField(blank=True, default=10, null=True)),
                ('commission_check_no', models.IntegerField(blank=True, null=True)),
                ('commission_paid', models.BooleanField(default=False)),
                ('sound_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sound_check_no', models.IntegerField(blank=True, null=True)),
                ('in_ears_cost', models.IntegerField(blank=True, choices=[(80, b'$80'), (130, b'$130')], default=130, null=True)),
                ('in_ears_check_no', models.IntegerField(blank=True, null=True)),
                ('costs_itemized', models.BooleanField(default=False)),
                ('print_ship_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ads_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('to_account', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subs', models.BooleanField(default=False)),
                ('settlement_sheet', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'receipts/')),
                ('payout_notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_agent', to='fidouche.Agent')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_image', models.ImageField(blank=True, upload_to=b'venues/')),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AS', b'American Samoa'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'AA', b'Armed Forces Americas'), (b'AE', b'Armed Forces Europe'), (b'AP', b'Armed Forces Pacific'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'GU', b'Guam'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'MP', b'Northern Mariana Islands'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'PR', b'Puerto Rico'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VI', b'Virgin Islands'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')], max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default=b'U.S.A.', max_length=100, null=True)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ltlng', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['venue_name'],
            },
        ),
        migrations.AddField(
            model_name='show',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_in_tour', to='shows.Tour'),
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows.Venue'),
        ),
    ]
