# Generated by Django 4.0.10 on 2026-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
