# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
                ('show', models.ManyToManyField(blank=True, to='shows.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('downloadable', models.FileField(upload_to=b'dl/')),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=b'images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('albums', models.ManyToManyField(blank=True, to='media.Album')),
                ('show', models.ManyToManyField(blank=True, to='shows.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('url', models.URLField()),
                ('vid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('embed_type', models.CharField(blank=True, choices=[(b'yt', b'YouTube'), (b'fb', b'Facebook'), (b'vm', b'Vimeo'), (b'o', b'other')], default=b'yt', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('albums', models.ManyToManyField(blank=True, to='media.Album')),
                ('show', models.ManyToManyField(blank=True, to='shows.Show')),
                ('tags', models.ManyToManyField(blank=True, to='media.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.Tag'),
        ),
        migrations.AddField(
            model_name='download',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.Tag'),
        ),
    ]
